// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkDbIswTeo_Sqv5BHhJD_vN-csb-zQKs',
    appId: '1:923604331995:web:744bf93be6266ee9ac8bfe',
    messagingSenderId: '923604331995',
    projectId: 'rent-app-migara',
    authDomain: 'rent-app-migara.firebaseapp.com',
    storageBucket: 'rent-app-migara.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwernXqu0KX4BUrzQOrFRwgQzSGj645ko',
    appId: '1:923604331995:android:236333c89036f453ac8bfe',
    messagingSenderId: '923604331995',
    projectId: 'rent-app-migara',
    storageBucket: 'rent-app-migara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllFBx2Fgu5_80UsoDkur_QJKV6aJp7gU',
    appId: '1:923604331995:ios:763910bd6d79e696ac8bfe',
    messagingSenderId: '923604331995',
    projectId: 'rent-app-migara',
    storageBucket: 'rent-app-migara.appspot.com',
    iosBundleId: 'lk.migara.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBllFBx2Fgu5_80UsoDkur_QJKV6aJp7gU',
    appId: '1:923604331995:ios:763910bd6d79e696ac8bfe',
    messagingSenderId: '923604331995',
    projectId: 'rent-app-migara',
    storageBucket: 'rent-app-migara.appspot.com',
    iosBundleId: 'lk.migara.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGkDbIswTeo_Sqv5BHhJD_vN-csb-zQKs',
    appId: '1:923604331995:web:c94c6e8f8107559aac8bfe',
    messagingSenderId: '923604331995',
    projectId: 'rent-app-migara',
    authDomain: 'rent-app-migara.firebaseapp.com',
    storageBucket: 'rent-app-migara.appspot.com',
  );
}
